// Code generated by goctl. DO NOT EDIT.
// Source of truth: api/desc/*.api — change fields there, then `make gen`.
// Scaffold keeps an empty types package until business .api files are added.

package types
