# golangci-lint v1.55.x（与 make tools 安装版本对齐）
run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  staticcheck:
    checks: ["all"]

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
