// Code generated by goctl — 中间件与 /health 以 scripts/handwritten/routes.go.in 为准。
// make gen 结束后会用 routes.go.in 覆盖本产物；请勿只改本模板期望生效。
// goctl {{.version}}

package handler

import (
	"net/http"{{if .hasTimeout}}
	"time"{{end}}

	{{.importPackages}}
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	{{.routesAdditions}}
}
